name:                4D
version:             0.1.0.0
github:              "wdhg/4D"
license:             BSD3
author:              "wdhg"
maintainer:          "example@example.com"
copyright:           "2020 wdhg"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/wdhg/4D#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  4D-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 4D

tests:
  4D-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 4D
    - HUnit
